name: Build website

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'
    branches: [ main ]
  # enable manual workflow trigger
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Set always-auth in npmrc
          always-auth: false # optional, default is false
          # Version Spec of the version to use.  Examples: 22.x, 20.15.1, >=20.15.0
          node-version: 22.x # optional
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
          architecture: x64
      - run: |
          echo "building systemds website"
          sudo gem install jekyll
          sudo npm install -g gulp
          npm install
          gulp build

